app/assets/javascripts/app/services/modelManager.js
Sorts tags by their lowercase title as new tags are added. 
Todo: render newly added tags according to the sort order.
=> Sort tags by name

app/assets/javascripts/app/frontend/controllers/editor.js
fix https://github.com/standardnotes/web/issues/26
=> Insert 4 spaces when tab key is pressed

Gemfile, README.md, circle.yml, karma.conf.js, package.json, test/javascripts/controllers/HomeCtrl_spec.js, test/javascripts/filters/DateFilter_spec.js
- Unit/Integration(ish) tests for Home Controller
- Simple test for the date filter
- Dependencies for Karma and Jasmine
- circle.yml file for CI
Fix https://github.com/standardnotes/web/issues/37
=> First pass at testing

package.json
Shouldn't Bower be in the list of devDependencies?
=> Add Bower to list of devDependencies

app/assets/javascripts/app/services/helpers/webcrypto.js
https://blog.standardnotes.org/important-updates-to-passwords-with-international-characters
=> UTF8 Encoding fix

app/assets/templates/frontend/directives/account-menu.html.haml
The Change Password and Import Password fields should not be plain text fields.
=> Use password field type for passwords

docker/entrypoint
added line in docker/entrypoint that enables clean restarting of the application without causing a boot loop
=> Fix Docker restart issue

LICENSE, package.json
Fix spacing in LICENSE file
Update license in [`package.json`](https://github.com/tjrana/web/blob/25d7588693d99cd4fcb55733fc0cfae729326ad0/package.json#L49) (Refer to [npm documentation](https://docs.npmjs.com/files/package.json) and [SPDX license list](https://spdx.org/licenses/))
Close standardnotes/web#241
=> Fix LICENSE

app/assets/javascripts/controllers/notes/note_utils.js, app/assets/javascripts/directives/views/componentView.js
This reverts commit c0759980cccbac53945e7bf58a6b0e25b93f63d8 and also disables linting for the cases involved.
=> Revert "eslint --fix: 'expression ? true : false' => '!!expression'"

app/assets/javascripts/controllers/root.js
This should fix the issue where the demo app fails to log in. It seems to have been caused by initializing parts of the Root controller in the wrong order. There are a lot of moving parts involved and I did not feel confident to do much more than rewrite the auto-signin method to make it clearer, and switch the initialization method calls around
=> Fix auto-signin

app/assets/javascripts/directives/views/editorMenu.js
=> Fix unable to 'undefault' editor 

app/assets/javascripts/controllers/notes/notes.js, app/assets/templates/notes.pug
Fixes #364.
Now when you click the "+" button while a search is active, it creates a new note with the name of the search.
=> Create a new note from search

app/assets/javascripts/controllers/notes/notes.js
=> Fix: Can't create new note inside View

README.md
TIL there's self-hosting for this project, btw!
=> Fix broken self-hosting link

app/assets/javascripts/controllers/lockScreen.js, app/assets/javascripts/directives/views/accountMenu.js, app/assets/templates/directives/account-menu.pug
- Fixes #386 
- Clears password after a failed login attempt 
- Clears password or when the user clicks on "cancel" from the login/register form
=> Clear password/passcode field

app/assets/javascripts/ui_models/application_group.ts
This PRs adds cleanup for observers and additionally avoids observers being notified twice with the same result.
=> feature: application group improvements

app/assets/javascripts/directives/views/accountMenu.ts
Related: https://github.com/standardnotes/snjs/pull/34
=> fix: when importing should prompt for password if keyParams is present

README.md, docker-compose.yml
Add docker-compose to build and run the app locally easier
=> feat: add docker-compose setup

app/assets/javascripts/directives/views/actionsMenu.ts, app/assets/templates/directives/actions-menu.pug
=> fix: actions not loading

app/assets/javascripts/services/preferencesManager.ts
I also had issues when preferences would note load for user after sign in, please check it after.
=> fix: unsubscribe streamItems on deinit

README.md
=> fix the docker-compose steps

.dockerignore, .env.sample, README.md, docker-compose.yml, docker/entrypoint.sh
Fixed local docker-compose setup and readme instructions to not confuse users anymore
=> fix: local docker-compose setup

app/assets/javascripts/directives/views/accountMenu.ts, app/assets/javascripts/strings.ts
@mobitar I changed the wording slightly from the master pull request, let me know if you agree with it.
=> fix: display error message if backup file is from an unsupported version

app/assets/javascripts/directives/views/accountMenu.ts, app/assets/javascripts/directives/views/actionsMenu.ts, app/assets/javascripts/directives/views/passwordWizard.ts, app/assets/javascripts/services/alertService.ts, app/assets/javascripts/services/autolock_service.ts, app/assets/javascripts/services/themeManager.ts, app/assets/javascripts/strings.ts, app/assets/javascripts/ui_models/application.ts, app/assets/javascripts/views/abstract/pure_view_ctrl.ts, app/assets/javascripts/views/application/application_view.ts, app/assets/javascripts/views/challenge_modal/challenge-modal.pug, app/assets/javascripts/views/challenge_modal/challenge_modal.ts, app/assets/javascripts/views/footer/footer_view.ts, app/assets/javascripts/views/notes/note_utils.ts, app/assets/stylesheets/_modals.scss, app/assets/stylesheets/_ui.scss, app/assets/templates/directives/account-menu.pug, app/assets/templates/directives/password-wizard.pug, dist/@types/app/assets/javascripts/services/autolock_service.d.ts, dist/@types/app/assets/javascripts/services/statusManager.d.ts, dist/@types/app/assets/javascripts/strings.d.ts, dist/@types/app/assets/javascripts/ui_models/application.d.ts, dist/@types/app/assets/javascripts/views/abstract/pure_view_ctrl.d.ts, package-lock.json, package.json
Handles SNJS custom challenge support as implemented in https://github.com/standardnotes/snjs/pull/112.
=> feat: custom challenges

.github/workflows/pr.yml, .github/workflows/prod.yml, README.md, config/deploy.rb
Once we get this PR to a mergeable state I'll update the branch name and _then_ merge this in, which I believe should trigger a deploy :)
=> fix: rename master branch to main

app/assets/javascripts/views/editor/editor_view.ts
=> feat: show offline status in saving indicator

.github/codeql/codeql-config.yml, .github/codeql/custom-queries/javascript/qlpack.yml, .github/workflows/codeql-analysis.yml, .gitignore, .npmignore, .prettierignore
Adds code analysis via CodeQL. The following queries are used:
- `security-and-quality`: queries from security-extended, plus maintainability and reliability queries
- custom queries located in [.github/codeql/custom-queries/javascript](https://github.com/standardnotes/web/tree/codeql-analysis/.github/codeql/custom-queries/javascript).
See the [code scanning alerts generated by this PR](https://github.com/standardnotes/web/security/code-scanning?query=ref%3Arefs%2Fpull%2F548%2Fmerge).
=> chore: codeql analysis action

package.json, yarn.lock
Upgrade/updates on SNJS package version should be intentional and not accidental.
=> fix: lock on snjs version

.env.sample, README.md, app/assets/javascripts/app.ts, app/assets/javascripts/startApplication.ts, app/assets/javascripts/ui_models/application.ts, app/assets/javascripts/ui_models/application_group.ts, app/views/application/app.html.erb, package.json
relates to: https://github.com/standardnotes/snjs/pull/319
=> feat: add alternative server for purposes of switching to API v1

.env.sample, .gitmodules, README.md, app/assets/javascripts/services/nativeExtManager.ts, app/assets/javascripts/ui_models/application.ts, index.html
- Removed batch-manager submodule
- Removed batched manager related code
=> feat: remove batch manager

app/assets/javascripts/components/AutocompleteTagHint.tsx, app/assets/javascripts/components/AutocompleteTagInput.tsx, app/assets/javascripts/components/AutocompleteTagResult.tsx, app/assets/javascripts/components/NoteTag.tsx
- fix: fix tags keyboard navigation
- fix: don't clear search query when navigating back to input
Fixes #589
=> fix: fix tags navigation

app/assets/javascripts/directives/views/componentView.ts, app/assets/templates/directives/component-view.pug, package.json, yarn.lock
=> feat: show deprecation notice

.env.sample, app/assets/javascripts/ui_models/app_state/app_state.ts, app/assets/javascripts/views/footer/footer-view.pug, app/views/application/app.html.erb, index.html
- Implemented enableUnfinishedFeatures flag, applied as env var and cascades to AppState where it can be read
- Implemented rudimentary Preferences button to show/hide preferences screen, currently it fails silently since the preferences screen is in another PR
=> feat: enableUnfinishedFeatures flag and hidden preferences button

app/views/application/app.html.erb
Fixes missing check of enable_unfinished_features in ruby template.
=> fix: enable_unfinished_features in ruby template

app/assets/javascripts/views/notes/notes_view.ts
- Implemented a fix which no longer redirects focus when a placeholder note is created
=> fix: creating placeholder note redirects focus

app/assets/javascripts/components/Button.tsx, app/assets/javascripts/components/ConfirmSignoutModal.tsx, app/assets/javascripts/components/ConfirmationDialog.tsx, app/assets/javascripts/components/OtherSessionsLogout.tsx, app/assets/javascripts/components/SessionsModal.tsx, app/assets/javascripts/preferences/PreferencesView.tsx, app/assets/javascripts/preferences/PreferencesViewWrapper.tsx, app/assets/javascripts/preferences/components/PreferencesGroup.tsx, app/assets/javascripts/preferences/components/PreferencesPane.tsx, app/assets/javascripts/preferences/components/PreferencesSegment.tsx, app/assets/javascripts/preferences/components/index.ts, app/assets/javascripts/preferences/panes/AccountPreferences.tsx, app/assets/javascripts/preferences/panes/account/LogOutView.tsx, app/assets/javascripts/preferences/panes/account/index.ts, app/assets/javascripts/ui_models/app_state/account_menu_state.ts, app/assets/javascripts/ui_models/app_state/app_state.ts, app/assets/stylesheets/_sn.scss, package.json, yarn.lock
Implemented Log out in Preferences -> Account: 
- Logging out of current session  
- Logging out of all other sessions
- Manage sessions
=> feat: implement UI for logging out

app/assets/javascripts/preferences/panes/Security.tsx, app/assets/javascripts/preferences/panes/security-segments/Protections.tsx, app/assets/javascripts/preferences/panes/security-segments/index.ts
- Implement protections segment in preferences.
=> feat: protections segment in preferences

app/assets/javascripts/preferences/panes/Security.tsx, app/assets/javascripts/preferences/panes/security-segments/DataBackups.tsx, app/assets/javascripts/preferences/panes/security-segments/index.ts
- Implemented a data backup export and import in Preferences segment
=> feat-preferences: data backup export and import

app/assets/javascripts/preferences/PreferencesView.tsx
- Implement closing preferences by clicking Escape
=> feat(preferences): close preferences with Esc button

app/assets/javascripts/preferences/components/Content.tsx, app/assets/javascripts/preferences/components/PreferencesPane.tsx, app/assets/javascripts/preferences/panes/AccountPreferences.tsx, app/assets/javascripts/preferences/panes/account/Authentication.tsx, app/assets/javascripts/preferences/panes/account/Credentials.tsx, app/assets/javascripts/preferences/panes/account/Sync.tsx, app/assets/javascripts/preferences/panes/account/index.ts, app/assets/javascripts/preferences/panes/account/subscription/Subscription.tsx, app/assets/stylesheets/_sn.scss
- Implement segment in preferences for a non-logged-in user
=> feat(preferences): not logged in segment

app/assets/icons/ic-check-bold.svg, app/assets/icons/ic-check.svg, app/assets/javascripts/components/Button.tsx, app/assets/javascripts/components/DecoratedInput.tsx, app/assets/javascripts/components/Input.tsx, app/assets/javascripts/components/shared/ModalDialog.tsx, app/assets/javascripts/preferences/components/Content.tsx, app/assets/javascripts/preferences/components/MenuItem.tsx, app/assets/javascripts/preferences/components/PreferencesPane.tsx, app/assets/javascripts/preferences/panes/security-segments/Encryption.tsx, app/assets/javascripts/preferences/panes/two-factor-auth/AuthAppInfoPopup.tsx, app/assets/javascripts/preferences/panes/two-factor-auth/Bullet.tsx, app/assets/stylesheets/_sn.scss
- Fix colour styles in Preferences so themes modify them appropriately
=> fix: use theme-modifiable colors

app/assets/javascripts/components/AccountMenu/index.tsx
- Removes unused variables from account menu. (The push hadn't come through in previous PR)
=> fix: remove unused vars in account menu

app/assets/stylesheets/_footer.scss
Before:
After:
(Asana task: https://app.asana.com/0/1160981203938995/1201243540845561)
=> fix: svg icons not showing on footer section

.env.sample, app/assets/javascripts/preferences/panes/account/subscription/SubscriptionInformation.tsx
Also add `DASHBOARD_URL` to `.env.sample`.
=> feat: Keep only "Manage subscription" button in account subscription prefs

app/assets/javascripts/components/QuickSettingsMenu.tsx, app/assets/stylesheets/_sn.scss
=> feat: Use toggle switch for layerable themes in quick settings menu

app/assets/javascripts/preferences/panes/security-segments/DataBackups.tsx, app/assets/javascripts/strings.ts
(Asana task: https://app.asana.com/0/1199914526147392/1201279540656598)
=> fix: show alert when importing a zip file as a backup

app/assets/javascripts/preferences/panes/account/subscription/Subscription.tsx, package.json, yarn.lock
Pending @standardnotes/snjs 2.17.4 deploy
=> fix: reload subscription state after event

app/assets/javascripts/purchaseFlow/PurchaseFlowView.tsx, app/assets/javascripts/purchaseFlow/panes/CreateAccount.tsx, app/assets/javascripts/purchaseFlow/panes/SignIn.tsx, app/assets/stylesheets/_sn.scss
Asana task: https://app.asana.com/0/0/1201355405905128/f
=> feat: Make purchase flow modal mobile-friendly

app/assets/javascripts/components/shared/ModalDialog.tsx, app/assets/javascripts/preferences/panes/account/changeEmail/index.tsx
Asana task: https://app.asana.com/0/0/1201367224120366/f
=> fix: Two-factor activation modal

app/assets/javascripts/preferences/panes/account/Authentication.tsx, app/assets/stylesheets/_sn.scss, app/assets/svg/il-account.svg
Asana task: https://app.asana.com/0/0/1201361332375411/f
=> feat: Use new design for signed out pane in preferences

app/assets/javascripts/preferences/panes/Extensions.tsx, app/assets/javascripts/preferences/panes/account/Advanced.tsx, app/assets/javascripts/preferences/panes/account/offlineSubscription.tsx
Internal link - https://app.asana.com/0/1200588672119490/1201372215255305
=> fix: hide horizontal separator if "offline subscriptions" section is hidden

app/assets/javascripts/components/NotesOptions.tsx
https://app.asana.com/0/1200980603427038/1201375312444547
=> fix: show correct "Last modified date" for note

app/assets/javascripts/preferences/panes/two-factor-auth/ScanQRCode.tsx, app/assets/stylesheets/_sn.scss
(Asana task: https://app.asana.com/0/1160983365020104/1179021867564307)
=> fix: add border to generated 2FA QR code

app/assets/javascripts/components/AutocompleteTagHint.tsx, app/assets/javascripts/components/AutocompleteTagResult.tsx, app/assets/stylesheets/_sn.scss
Asana task: https://app.asana.com/0/0/1201428701500366/f
=> feat: Change bg color when focusing tag instead of border

app/assets/stylesheets/_sn.scss
Asana task: https://app.asana.com/0/0/1201474967876287/f
=> fix: UI shiting when opening dropdown with a lot of items

app/assets/javascripts/components/NotesListOptionsMenu.tsx, app/assets/javascripts/components/QuickSettingsMenu/QuickSettingsMenu.tsx
1. feat: Add keyboard nav for toggleable components
2. feat: Cleanup item streams on re-renders
3. feat: Close notes display options menu if clicked outside
=> feat: Multiple minor changes

app/assets/javascripts/components/AccountMenu/GeneralAccountMenu.tsx, app/assets/stylesheets/_sn.scss
Asana task: https://app.asana.com/0/1160981203938995/1201487837010240/f
=> fix: Last sync date padding

app/assets/javascripts/components/AutocompleteTagResult.tsx, app/assets/javascripts/components/NoteTag.tsx, app/assets/javascripts/ui_models/app_state/note_tags_state.ts, app/assets/javascripts/ui_models/app_state/tags_state.ts
Related Tasks:
- https://app.asana.com/0/1201541865782599/1201545498356894
- https://app.asana.com/0/1201409453293587/1201541865782614
- https://app.asana.com/0/1201409453293587/1201541865782616
=> feat: allows duplicate names in tags folder & smart tags

app/assets/javascripts/ui_models/app_state/notes_state.ts
Internal link: https://app.asana.com/0/1200588672119490/1201456521732291
=> fix: update selected notes count when deleting multiple notes permanently

app/assets/javascripts/components/Tags/RootTagDropZone.tsx, app/assets/javascripts/components/Tags/TagsListItem.tsx, app/assets/javascripts/ui_models/app_state/tags_state.ts
[Internal Link](https://app.asana.com/0/0/1201651196905125/f)
=> feat: display folders even without premium

app/assets/javascripts/components/NotesList.tsx, app/assets/stylesheets/_notes.scss
[Internal link](https://app.asana.com/0/1201653402817577/1201722077552522/f)
=> fix: Notes list options menu getting hidden

app/assets/javascripts/components/NotesList.tsx, app/assets/javascripts/components/NotesOptions/ChangeEditorOption.tsx, app/assets/javascripts/components/NotesOptions/changeEditor/EditorAccordionMenu.tsx, app/assets/javascripts/views/constants.ts, app/assets/stylesheets/_sn.scss
[Internal link](https://app.asana.com/0/1201611182420182/1201681453954495/f)
=> feat: improve change editor menu keyboard navigation

app/assets/javascripts/components/NotesOptions/NotesOptions.tsx, app/assets/stylesheets/_sn.scss
[Internal link](https://app.asana.com/0/1201611182420182/1201744357670153/f)
=> feat: make whole menu switch be clickable

app/assets/javascripts/components/NotesView.tsx
[Internal link](https://app.asana.com/0/1201653402817577/1201754780922633/f)
=> fix: options button text color

app/assets/javascripts/preferences/panes/backups-segments/EmailBackups.tsx, app/assets/javascripts/preferences/panes/backups-segments/cloud-backups/CloudBackupProvider.tsx, app/assets/javascripts/preferences/panes/backups-segments/cloud-backups/index.tsx, package.json, yarn.lock
[Internal link](https://app.asana.com/0/1201653402817577/1201753231276676)
=> fix: don't get backups settings if there is no logged-in user

app/assets/javascripts/preferences/panes/backups-segments/cloud-backups/index.tsx
[Internal link](https://app.asana.com/0/1201653402817577/1201753231276676)
=> fix: correctly check if cloud backups are available for the user

app/assets/javascripts/components/NotesOptions/NotesOptions.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1201767728576417/f)
=> feat: move change editor up in menu

app/assets/javascripts/components/NotesList.tsx
[Internal link](https://app.asana.com/0/1201653402817568/1201762958843233/f)
=> feat: sort note cell tags alphabetically

app/assets/javascripts/components/NotesListItem.tsx, app/assets/stylesheets/_notes.scss
[Internal link](https://app.asana.com/0/1201653402817568/1201771943311068/f)
=> fix: notes list item layout when title is empty

app/assets/javascripts/components/ApplicationView.tsx, app/assets/javascripts/components/Navigation.tsx, app/assets/javascripts/components/NotesOptions/ChangeEditorOption.tsx, app/assets/javascripts/components/QuickSettingsMenu/FocusModeSwitch.tsx, app/assets/javascripts/components/QuickSettingsMenu/QuickSettingsMenu.tsx, app/assets/javascripts/components/QuickSettingsMenu/ThemesMenuButton.tsx, app/assets/javascripts/preferences/panes/Appearance.tsx
[Internal link](https://app.asana.com/0/1201653402817568/1201758447368758/f)
=> feat: show all themes in quick settings menu and premium icon if not entitled to theme

app/assets/stylesheets/_notes.scss
https://github.com/standardnotes/web/issues/873
=> fix: use break-word for note list item title; closes #873

app/assets/javascripts/ui_models/app_state/tags_state.ts
[Internal link](https://app.asana.com/0/1201653402817577/1201833540317489/f)
=> refactor: move setting allNotesCount_ into action

app/assets/javascripts/components/RevisionHistoryModal/SelectedRevisionContent.tsx, app/assets/stylesheets/_sn.scss
[Internal link](https://app.asana.com/0/0/1201844261934883/f)
=> fix: plain editor revision rendering

app/assets/javascripts/components/NotesOptionsPanel.tsx
[Internal link](https://app.asana.com/0/1201404190373500/1201762525203438/f)
=> fix: notes options closing when selecting note id

app/assets/javascripts/components/Tags/TagContextMenu.tsx
[Internal link](https://app.asana.com/0/1201653402817568/1201831657647591/f)
=> fix: tag context menu

app/assets/javascripts/components/NotesOptions/ListedActionsOption.tsx
[Internal link](https://app.asana.com/0/1201653402817577/1201878961837312/f)
=> feat: make listed menu sorting consistent

app/assets/javascripts/components/NotesOptions/ChangeEditorOption.tsx
[Internal link](https://app.asana.com/0/1201653402817577/1201878793085520/f)
=> feat: use improved style calculation for change editor submenu

app/assets/javascripts/components/RevisionHistoryModal/HistoryListContainer.tsx, app/assets/javascripts/components/RevisionHistoryModal/LegacyHistoryList.tsx, app/assets/javascripts/components/RevisionHistoryModal/RemoteHistoryList.tsx, app/assets/javascripts/components/RevisionHistoryModal/SessionHistoryList.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1201844169174294/f)
=> fix: first history entry being fetched twice

app/assets/javascripts/components/ChangeEditorButton.tsx, app/assets/javascripts/components/NotesOptions/ChangeEditorOption.tsx, app/assets/javascripts/components/NotesOptions/changeEditor/ChangeEditorMenu.tsx
[Internal link](https://app.asana.com/0/1201653402817577/1201913530121972/f)
=> feat: close change editor menu once editor is selected

app/assets/javascripts/components/NotesListOptionsMenu.tsx, app/assets/stylesheets/_sn.scss
[Internal link](https://app.asana.com/0/1201653402817577/1201923156365086/f)
=> fix: notes list options menu size regression

app/assets/javascripts/components/NotesOptions/AddTagOption.tsx, app/assets/javascripts/components/NotesOptions/ChangeEditorOption.tsx, app/assets/javascripts/components/NotesOptions/ListedActionsOption.tsx, app/assets/javascripts/components/NotesOptions/NotesOptions.tsx, app/assets/javascripts/components/NotesOptionsPanel.tsx, app/assets/javascripts/components/menu/Menu.tsx, app/assets/javascripts/components/utils.ts
[Internal link](https://app.asana.com/0/1201404190373500/1201876460433517/f)
=> feat: close submenu if another submenu is opened

app/assets/javascripts/preferences/panes/general-segments/Labs.tsx
- fix: experimental features not reloading after toggling
- fix: render "No experimental features available." message inside `PreferencesSegment`
=> fix: experimental features not reloading after toggling

app/assets/javascripts/components/NotesView.tsx
[Internal link](https://app.asana.com/0/1201653402817568/1201955789467725/f)
=> feat: disable autocomplete for search input

app/assets/javascripts/components/AttachedFilesPopover/PopoverFileItem.tsx
[Internal link](https://app.asana.com/0/1199942776723820/1201952151327795/f)
=> fix: make file renaming consistent with tag & note renaming

app/assets/javascripts/components/AttachedFilesPopover/AttachedFilesButton.tsx, app/assets/javascripts/components/NoteView/NoteView.tsx, app/assets/stylesheets/_sn.scss
[Internal link](https://app.asana.com/0/1199942776723820/1201960955990955/f)
=> fix: file drag-n-drop issue

app/assets/javascripts/components/NotesOptions/NotesOptions.tsx, app/assets/javascripts/services/archiveManager.ts, package.json, yarn.lock
[Internal link](https://app.asana.com/0/1201404190373500/1201863323887809/f)
=> feat: export as zip if multiple notes are selected

app/assets/stylesheets/_notes.scss
[Internal link](https://app.asana.com/0/1201653402817568/1202015218540082/f)
=> fix: progress bar color on firefox

app/assets/javascripts/components/Footer.tsx, package.json, yarn.lock
[Internal link](https://app.asana.com/0/1201653402817568/1202015218540090/f)
=> chore: upgrade snjs

app/assets/javascripts/components/NoteView/NoteView.tsx
[Internal link](https://app.asana.com/0/1201653402817568/1202059972736305/f)
=> feat: disable note title input autocomplete

app/assets/javascripts/components/RevisionHistoryModal/SelectedRevisionContent.tsx
Fixes note revision textarea background color for non-default themes.
=> fix: revision textarea background color

app/assets/javascripts/Services/ThemeManager.ts
[Internal link](https://app.asana.com/0/0/1202049103273894/1202124334574789/f)
=> fix: only show color scheme toast if change is required

package.json, yarn.lock
[Internal link](https://app.asana.com/0/1201653402817568/1202124930274897/f)
=> fix: focus trap error

app/assets/javascripts/Components/Preferences/Panes/Security/Encryption.tsx, app/assets/stylesheets/_sn.scss
[Internal link](https://app.asana.com/0/1201653402817568/1202124334574790/f)
=> fix: encryption section styles

app/assets/javascripts/Components/Preferences/Panes/Listed/index.tsx, app/assets/javascripts/Components/Preferences/Panes/Security/index.tsx
[Internal link](https://app.asana.com/0/1201653402817568/1202117823133266/f)
=> feat: hide some prefs if not logged in

config/application.rb
[Internal link](https://app.asana.com/0/1199942776723820/1202138287571277/f)
=> fix: video preview csp error

app/assets/javascripts/Components/Files/FilePreviewModal.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1202163228064396/f)
=> fix: "file can't be previewed" flashing

app/assets/javascripts/Components/AttachedFilesPopover/AttachedFilesButton.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1202178314278379/f)
=> fix: sync request before downloading/previewing file

app/assets/javascripts/Components/Files/FilePreviewModal.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1202178314278385/f)
=> fix: spinner loading infinitely on unsupported file types

app/assets/javascripts/Components/Preferences/Panes/Account/Files.tsx, app/assets/javascripts/Components/Preferences/Panes/Account/index.tsx
[Internal link](https://app.asana.com/0/0/1202178087152257/1202190736187275/f)
=> fix: duplicate files quota calls in preferences

app/assets/javascripts/Components/AttachedFilesPopover/AttachedFilesButton.tsx, app/assets/javascripts/Components/AttachedFilesPopover/AttachedFilesPopover.tsx, app/assets/javascripts/Components/Files/FilePreviewModal.tsx, app/assets/javascripts/Components/Files/FilePreviewModalProvider.tsx, app/assets/javascripts/Services/IOService.ts
[Internal link](https://app.asana.com/0/1201611182420182/1202165057796967/f)
=> feat: preview next/prev files using arrow keys

app/assets/javascripts/UIModels/AppState/FilesState.ts, package.json, yarn.lock
[Internal link](https://app.asana.com/0/1201611182420182/1202187771437530/f)
=> feat: show download/upload progess in toast

app/assets/javascripts/Services/IOService.ts
[Internal link](https://app.asana.com/0/1201611182420182/1202218710971649/f)
=> fix: modifier-only key observers not working

app/assets/javascripts/Components/Files/FilePreviewModal.tsx, app/assets/javascripts/UIModels/AppState/FilesState.ts, config/application.rb
[Internal link](https://app.asana.com/0/1201611182420182/1202219361853075/f)
=> feat: show download progress in file preview modal

app/assets/javascripts/UIModels/AppState/FilesState.ts
[Internal link](https://app.asana.com/0/1199942776723820/1202245234835612/f)
=> fix: download success toast showing up even if download errors

app/assets/javascripts/Components/AttachedFilesPopover/AttachedFilesButton.tsx, app/assets/javascripts/Components/Files/FilePreviewModal.tsx
[Internal link](https://app.asana.com/0/1201653402817568/1202254390984710/f)
=> fix: bug when switching between previewable & non-previewable files

app/assets/javascripts/Components/AttachedFilesPopover/AttachedFilesButton.tsx, app/assets/javascripts/Hooks/useCloseOnBlur.ts
[Internal link](https://app.asana.com/0/1201653402817568/1202178314278381/f)
=> fix: popover closing on delete dialog

app/assets/javascripts/Components/AccountMenu/WorkspaceSwitcher/WorkspaceMenuItem.tsx, app/assets/javascripts/Components/ChangeEditor/ChangeEditorMenu.tsx, app/assets/javascripts/Components/Menu/MenuItem.tsx, app/assets/javascripts/Components/NotesList/NotesListOptionsMenu.tsx, app/assets/stylesheets/_sn.scss
[Internal link](https://app.asana.com/0/1201611182420182/1202302784497403/f)
=> feat: update note type menu design

app/assets/javascripts/Components/NoteView/NoteView.tsx, app/assets/javascripts/Components/NotesOptions/NotesOptions.tsx, app/assets/stylesheets/_sn.scss
=> feat: updated "note editing disabled" design

app/assets/javascripts/Components/Files/FilePreviewModal.tsx, app/assets/javascripts/Components/Files/PreviewComponent.tsx
[Internal link](https://app.asana.com/0/1201653402817568/1202314980723394/f)
=> feat: autoplay videos when previewing

app/assets/javascripts/Components/Files/ImagePreview.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1202313225686917/f)
=> fix: image zoom scroll

app/assets/javascripts/Components/ApplicationView/ApplicationView.tsx, app/assets/javascripts/Components/Files/FilePreviewModal.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1202324599716360/f)
=> fix: object url not being revoked on modal close

package.json, yarn.lock
[Internal link](https://app.asana.com/0/1201653402817568/1202341998636731/f)
=> fix: note tags list styling

app/assets/javascripts/Components/ContentListView/ContentListView.tsx
[Internal link](https://app.asana.com/0/0/1202315272822269/f)
=> feat: upload prompt on add button click in FilesView

app/assets/javascripts/Components/ContentListView/ContentListOptionsMenu.tsx, app/assets/javascripts/Components/ContentListView/ContentListView.tsx, app/assets/javascripts/Components/Menu/Menu.tsx
[Internal link](https://app.asana.com/0/0/1202315295894935/f)
=> fix: make display options copy type-agnostic

app/assets/javascripts/Components/ContentListView/ContentListItem.tsx, app/assets/javascripts/Components/ContentListView/ListItemTags.tsx, app/assets/javascripts/Components/ContentListView/Types/DisplayableListItemProps.ts
[Internal link](https://app.asana.com/0/1201653402817568/1202362376622429/f)
=> fix: list tags key warning

app/assets/javascripts/UIModels/AppState/ContentListViewState.ts
[Internal link](https://app.asana.com/0/1201611182420182/1202369650722995/f)
=> feat: switch to notes view when creating new note

app/assets/javascripts/Components/NoteTags/NoteTag.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1202389427235393/f)
=> fix: dom nesting error

packages/styles/src/Styles/_sn.scss, packages/web/src/javascripts/Components/Dropdown/Dropdown.tsx
Fixes files button padding and dropdown styles
=> fix: dropdown and files button ui

packages/web/src/javascripts/Components/RevisionHistoryModal/SessionHistoryList.tsx, packages/web/src/javascripts/Components/RevisionHistoryModal/utils.ts, packages/web/src/javascripts/Controllers/NoteHistory/NoteHistoryController.ts
[Internal link](https://app.asana.com/0/1201611182420182/1202128838771404/f)
=> fix: session history

packages/mobile/src/App.tsx, packages/mobile/src/EnvironmentContext.tsx, packages/mobile/src/Hooks/useSafeEnvironmentContext.ts, packages/mobile/src/Lib/Interface.ts, packages/mobile/src/Lib/constants.ts, packages/mobile/src/Screens/Settings/Sections/OptionsSection.tsx, packages/mobile/src/Screens/Settings/Settings.tsx
[Internal link](https://app.asana.com/0/1200588672119490/1202151423548069)
=> fix: use a specific feature flag for workspace

packages/mobile/src/Screens/Settings/Sections/OptionsSection.tsx
[Internal link](https://app.asana.com/0/1201653402817596/1202487434739124)
=> fix: restore top border of "Manage Sessions" row

packages/components/src/Packages/Themes/org.standardnotes.theme-autobiography/src/main.scss, packages/components/src/Packages/Themes/org.standardnotes.theme-focus/src/main.scss, packages/components/src/Packages/Themes/org.standardnotes.theme-futura/src/main.scss, packages/components/src/Packages/Themes/org.standardnotes.theme-midnight/src/main.scss, packages/components/src/Packages/Themes/org.standardnotes.theme-solarized-dark/src/main.scss, packages/components/src/Packages/Themes/org.standardnotes.theme-titanium/src/main.scss, packages/web/src/stylesheets/_theme.scss
[Internal link](https://app.asana.com/0/1201653402817568/1202529212586263/f)
=> fix(web): selected navigation item color

packages/web/src/javascripts/Components/FileView/FileViewWithoutProtection.tsx
[Internal link](https://app.asana.com/0/0/1202495757427487/1202495757427492/f)
=> feat(web): file view auto-rename on title change, similar to note view

packages/web/src/javascripts/Components/ApplicationView/ApplicationView.tsx, packages/web/src/javascripts/Components/AttachedFilesPopover/AttachedFilesButton.tsx, packages/web/src/javascripts/Components/FileDragNDropProvider/FileDragNDropProvider.tsx, packages/web/src/javascripts/Components/FileView/FileViewWithoutProtection.tsx, packages/web/src/javascripts/Components/MultipleSelectedFiles/MultipleSelectedFiles.tsx, packages/web/src/javascripts/Components/NoteGroupView/NoteGroupView.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1202495757427487/f)
Removes the need to have the attached files button for file drag-n-drop to work.
=> feat: file drag-n-drop provider

packages/web/src/javascripts/Components/NoteGroupView/NoteGroupView.tsx, packages/web/src/javascripts/Components/PermissionsModal/PermissionsModal.tsx, packages/web/src/javascripts/Components/PermissionsModal/PermissionsModalWrapper.tsx, packages/web/src/javascripts/Components/Preferences/Panes/General/Advanced/Packages/ConfirmCustomPackage.tsx
[Internal link](https://app.asana.com/0/1201653402817568/1202540902894921/f)
=> fix: permissions modal width

packages/web/src/javascripts/Components/NoAccountWarning/NoAccountWarningContent.tsx, packages/web/src/stylesheets/_navigation.scss, packages/web/src/stylesheets/index.css.scss
Fixes scrollbar styles and no account warning shadow.
[Internal link](https://app.asana.com/0/1201653402817568/1202561835289746/f)
=> fix(web): scrollbar styles

packages/models/package.json, packages/models/src/Domain/Runtime/Display/ItemDisplayController.ts, packages/web/src/javascripts/Components/FileContextMenu/FileMenuOptions.tsx, packages/web/src/javascripts/Controllers/Navigation/NavigationController.ts, yarn.lock
[Internal link](https://app.asana.com/0/1201611182420182/1202533538845877/f)
=> fix: subtag duplication

packages/desktop/app/stylesheets/renderer.css, packages/web/src/javascripts/Components/Navigation/Navigation.tsx, packages/web/src/javascripts/Components/SearchBar/SearchBar.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1202567330188851/f)
=> fix(desktop): only shift down sections on macOS if window is big enough

packages/web/src/javascripts/Components/TagAutocomplete/AutocompleteTagInput.tsx
[Internal link](https://app.asana.com/0/1201653402817568/1202584105110227)
=> fix(web): responsive autocomplete tag dropdown

packages/web/src/javascripts/Components/Popover/Popover.tsx, packages/web/src/javascripts/Components/Popover/PositionedPopoverContent.tsx, packages/web/src/javascripts/Components/Popover/Types.ts, packages/web/src/javascripts/Components/Popover/Utils/usePopoverCloseOnClickOutside.ts
[Internal link](https://app.asana.com/0/1201611182420182/1202660949344886/f)
=> fix: popover behaviour when clicking outside of popover

packages/web/src/javascripts/App.tsx, packages/web/src/javascripts/Utils/Utils.ts
[Internal link](https://app.asana.com/0/1201611182420182/1202734831899646)
=> fix: disable zoom on input focusing on ios

packages/web/src/javascripts/Components/Tags/TagsListItem.tsx
[Internal link](https://app.asana.com/0/1202707201988678/1202770610092974/f)
=> fix: tag context menu button opening notes list veiw

packages/web/src/javascripts/Components/Tags/SmartViewsListItem.tsx, packages/web/src/javascripts/Components/Tags/TagsListItem.tsx
[Internal link](https://app.asana.com/0/1202707201988678/1202770610092968/f)
=> fix: tags being dimmed on safari

packages/web/src/javascripts/Components/AttachedFilesPopover/AttachedFilesPopover.tsx, packages/web/src/javascripts/Components/ContentListView/ContentListView.tsx, packages/web/src/javascripts/Controllers/FilesController.ts
[Internal link](https://app.asana.com/0/1201611182420182/1202770610092976/f)
=> fix: selecting from "Photo Library" on iOS doesn't upload

packages/web/src/javascripts/Components/NoteTags/NoteTag.tsx, packages/web/src/javascripts/Components/TagAutocomplete/AutocompleteTagResult.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1202770610092972/f)
=> fix: note tag delete button not showing on iOS

packages/web/src/javascripts/Components/AttachedFilesPopover/AttachedFilesPopover.tsx, packages/web/src/javascripts/Components/ContentListView/ContentListView.tsx
Fixes: https://discord.com/channels/894600255058898974/910196436065452103/1009508221796499456
=> fix: hidden file input being clickable

packages/components/src/Packages/Editors/org.standardnotes.token-vault/app/components/QRCodeReader.jsx
[Internal link](https://app.asana.com/0/1200588672119490/1202668014907248)
=> fix: trigger the `onChange` event of qr code uploading input when clicking on the button

packages/components/src/Packages/Editors/org.standardnotes.simple-task-editor/app/stylesheets/main.scss
[Internal link](https://app.asana.com/0/1202876216397978/1202929351208030/f)
=> fix: add min-height to task textarea

packages/web/src/javascripts/Components/Footer/AccountMenuButton.tsx, packages/web/src/javascripts/Components/Footer/Footer.tsx, packages/web/src/javascripts/Components/Footer/QuickSettingsButton.tsx, packages/web/src/javascripts/Components/Preferences/PreferencesMenuView.tsx, packages/web/src/stylesheets/_footer.scss
[Internal link](https://app.asana.com/0/1202707201988678/1202770610092978/f)
=> fix: footer icons and prefs dropdown cutoff by screen on some phones

packages/web/package.json, packages/web/src/javascripts/Utils/ManageSubscription.ts
[Internal link](https://app.asana.com/0/1202879741468065/1202951983202328)
=> fix: ability to open a new tab on iOS Safari

packages/web/src/javascripts/App.tsx, packages/web/src/javascripts/Components/ContentListView/ContentList.tsx, packages/web/src/javascripts/Components/ContentListView/ContentListView.tsx, packages/web/src/javascripts/Components/ContentListView/Header/ContentListHeader.tsx, packages/web/src/javascripts/Components/FileView/FileViewWithoutProtection.tsx, packages/web/src/javascripts/Components/Footer/AccountMenuButton.tsx, packages/web/src/javascripts/Components/Footer/Footer.tsx, packages/web/src/javascripts/Components/Footer/QuickSettingsButton.tsx, packages/web/src/javascripts/Components/Icon/Icon.tsx, packages/web/src/javascripts/Components/Navigation/Navigation.tsx, packages/web/src/javascripts/Components/NavigationMenu/NavigationMenu.tsx, packages/web/src/javascripts/Components/NoteGroupView/NoteGroupView.tsx, packages/web/src/javascripts/Components/NoteView/NoteView.tsx, packages/web/src/javascripts/Components/ResponsivePane/ResponsivePaneContent.tsx, packages/web/src/javascripts/Components/Tags/SmartViewsListItem.tsx, packages/web/src/javascripts/Components/Tags/TagsListItem.tsx, packages/web/src/stylesheets/_columns.scss, packages/web/src/stylesheets/_main.scss, packages/web/src/stylesheets/_navigation.scss, packages/web/tailwind.config.js
[Internal link](https://app.asana.com/0/1201611182420182/1202953104531179/f)
=> feat: update mobile design

packages/web/src/javascripts/Components/Preferences/Panes/Security/TwoFactorAuth/ScanQRCode.tsx
[Internal link](https://app.asana.com/0/1202879741468065/1202962882780230)
=> fix: display QR codes with correctly colored border so that scanner apps successfully recognize them

packages/web/src/javascripts/Components/FileView/FileViewWithoutProtection.tsx, packages/web/src/javascripts/Components/NoteGroupView/MobileItemsListButton.tsx, packages/web/src/javascripts/Components/NoteGroupView/NoteGroupView.tsx, packages/web/src/javascripts/Components/NoteView/NoteView.tsx
[Internal link](https://app.asana.com/0/0/1202963980832754/1198709526921870/f)
=> fix: move mobile nav button next to note/file title

packages/mobile/src/Lib/Interface.ts, packages/services/src/Domain/Device/MobileDeviceInterface.ts, packages/web/src/javascripts/Components/ChallengeModal/ChallengeModal.tsx, packages/web/src/javascripts/Components/ChallengeModal/ChallengePrompt.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1202959197978283/f)
=> fix: biometrics input on mobile webview challenge modal

packages/web/src/javascripts/Components/FileView/FileViewWithoutProtection.tsx, packages/web/src/javascripts/Components/NoteView/NoteView.tsx
[Internal link](https://app.asana.com/0/1202876216397978/1202994846970441/f)
=> fix: long titles on non-mobile view

packages/web/src/javascripts/Components/Dropdown/Dropdown.tsx, packages/web/src/javascripts/Components/Preferences/PreferencesMenuView.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1202997136490877/f)
=> fix: preferences dropdown contrast and color

packages/web/src/javascripts/Components/ResponsivePane/ResponsivePaneProvider.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921876/f)
=> fix: default to notes list on launch on mobile

packages/web/src/javascripts/Components/ApplicationView/ApplicationView.tsx, packages/web/src/javascripts/Components/FileContextMenu/FileMenuOptions.tsx, packages/web/src/javascripts/Components/NotesContextMenu/NotesContextMenu.tsx, packages/web/src/javascripts/Components/NotesOptions/NotesOptions.tsx, packages/web/src/javascripts/Components/NotesOptions/NotesOptionsPanel.tsx, packages/web/src/javascripts/Components/NotesOptions/NotesOptionsProps.ts, packages/web/src/javascripts/Components/ResponsivePane/ResponsivePaneProvider.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921879/f)
=> fix: close menu & toggle notes list when note action occurs

packages/mobile/src/AppStack.tsx, packages/mobile/src/MobileWebAppContainer.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921877/f)
=> fix: iOS webview window size and padding

packages/web/src/javascripts/Components/AccountMenu/WorkspaceSwitcher/WorkspaceSwitcherMenu.tsx, packages/web/src/javascripts/Components/ConfirmSignoutModal/ConfirmSignoutModal.tsx
[Internal link](https://app.asana.com/0/0/1202997136490895/1203022896707213/f)
=> fix: revert alert changes

packages/web/src/javascripts/Components/Navigation/Navigation.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203022003122679/f)
=> feat: add lock button to navigation panel on mobile

packages/mobile/html/Web.bundle/src/index.html, packages/mobile/src/MobileWebAppContainer.tsx, packages/web/src/javascripts/Components/Popover/PositionedPopoverContent.tsx, packages/web/src/stylesheets/_main.scss, packages/web/tailwind.config.js
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921877/f)
=> fix: iOS safe area using CSS

packages/web/src/javascripts/Components/RevisionHistoryModal/HistoryListContainer.tsx, packages/web/src/javascripts/Components/RevisionHistoryModal/HistoryModalDialogContent.tsx, packages/web/src/javascripts/Components/RevisionHistoryModal/LegacyHistoryList.tsx, packages/web/src/javascripts/Components/RevisionHistoryModal/RemoteHistoryList.tsx, packages/web/src/javascripts/Components/RevisionHistoryModal/SessionHistoryList.tsx, packages/web/src/javascripts/Components/RevisionHistoryModal/utils.ts
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921885/f)
=> feat: on mobile goto content tab after selecting revision

packages/web/src/javascripts/Utils/ManageSubscription.ts
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921882/f)
=> fix: manage subscription button on mobile webview

packages/snjs/lib/Services/Settings/SettingsList.ts, packages/web/src/javascripts/Components/Preferences/Panes/General/Email.tsx, packages/web/src/javascripts/Components/Preferences/Panes/General/General.tsx, packages/web/src/javascripts/Components/Preferences/Panes/Security/Privacy.tsx, packages/web/src/javascripts/Controllers/PreferencesController.ts, packages/web/src/javascripts/Controllers/ViewControllerManager.ts
Reverts standardnotes/app#1617
=> Revert "Revert "feat(web): move emails notifications to one pane and enable opening settings via url""

packages/web/src/javascripts/Components/Navigation/Navigation.tsx, packages/web/src/javascripts/Components/Popover/GetPositionedPopoverStyles.ts, packages/web/src/javascripts/Components/Popover/PositionedPopoverContent.tsx, packages/web/src/javascripts/Components/Popover/Utils/Rect.ts, packages/web/src/javascripts/Components/Popover/Utils/usePopoverCloseOnClickOutside.ts, packages/web/src/javascripts/Components/Preferences/PreferencesView.tsx, packages/web/src/javascripts/Hooks/useMediaQuery.tsx, packages/web/src/javascripts/Utils/Utils.ts
[Internal link](https://app.asana.com/0/1202205071929494/1202999393884566/f)
=> fix: responsiveness when resizing window on web/desktop

packages/web/src/javascripts/Components/Footer/Footer.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203041228162564/f)
=> fix: move prefs button next to account menu button in footer

packages/web/src/javascripts/Components/NoteTags/NoteTag.tsx, packages/web/src/javascripts/Components/NoteTags/NoteTagsContainer.tsx, packages/web/src/javascripts/Components/NoteTags/NoteTagsPanel.tsx, packages/web/src/javascripts/Components/NoteView/NoteView.tsx, packages/web/src/javascripts/Components/Popover/PositionedPopoverContent.tsx, packages/web/src/javascripts/Components/TagAutocomplete/AutocompleteTagHint.tsx, packages/web/src/javascripts/Components/TagAutocomplete/AutocompleteTagInput.tsx, packages/web/src/javascripts/Components/TagAutocomplete/AutocompleteTagResult.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921895/f)
=> feat: note tags button for mobile

packages/mobile/src/AndroidBackHandlerService.ts, packages/mobile/src/Lib/Interface.ts, packages/mobile/src/MobileWebAppContainer.tsx, packages/services/src/Domain/Application/WebApplicationInterface.ts, packages/services/src/Domain/Device/MobileDeviceInterface.ts, packages/snjs/lib/Client/ReactNativeToWebEvent.ts, packages/web/src/javascripts/Application/Application.ts, packages/web/src/javascripts/Application/MobileWebReceiver.ts, packages/web/src/javascripts/Components/ApplicationView/ApplicationView.tsx, packages/web/src/javascripts/Components/ChallengeModal/ChallengeModal.tsx, packages/web/src/javascripts/Components/Popover/Popover.tsx, packages/web/src/javascripts/Components/Preferences/PreferencesView.tsx, packages/web/src/javascripts/Components/ResponsivePane/ResponsivePaneProvider.tsx, packages/web/src/javascripts/Components/RevisionHistoryModal/RevisionHistoryModal.tsx, packages/web/src/javascripts/Components/Shared/ModalDialogLabel.tsx, packages/web/src/javascripts/NativeMobileWeb/AndroidBackButtonHandler.tsx, packages/web/src/javascripts/NativeMobileWeb/AndroidBackHandler.tsx, packages/web/src/javascripts/NativeMobileWeb/useAndroidBackHandler.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203045073649291/f)
=> feat: handle android back button on android

packages/web/src/javascripts/Components/NoteView/NoteView.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203058057794105/f)
=> fix: sticky header behavior on iOS

packages/web/src/javascripts/Components/Navigation/Navigation.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203072614946039/f)
=> fix: navigation panel resizer not showing

packages/models/src/Domain/Syncable/UserPrefs/PrefKey.ts, packages/web/src/javascripts/Components/NoteView/AutoresizingTextarea.tsx, packages/web/src/javascripts/Components/NoteView/NoteView.tsx, packages/web/src/javascripts/Components/Preferences/Panes/General/General.tsx, packages/web/src/javascripts/Components/Preferences/Panes/General/PlaintextDefaults.tsx, packages/web/src/javascripts/Components/Preferences/Panes/General/Tools.tsx, packages/web/src/javascripts/Components/RevisionHistoryModal/SelectedRevisionContent.tsx, packages/web/src/javascripts/Constants/PrefDefaults.ts, packages/web/src/stylesheets/_editor.scss, packages/web/src/stylesheets/_main.scss, packages/web/src/stylesheets/_stylekit-sub.scss, packages/web/tailwind.config.js
[Internal link](https://app.asana.com/0/1201611182420182/1203022607956523/f)
=> feat: add line height & font size settings for plaintext editor

packages/models/src/Domain/Syncable/UserPrefs/PrefKey.ts, packages/web/src/javascripts/Components/NoteView/NoteStatusIndicator.tsx, packages/web/src/javascripts/Components/NoteView/NoteView.tsx, packages/web/src/javascripts/Components/Preferences/Panes/General/Tools.tsx, packages/web/src/javascripts/Constants/PrefDefaults.ts
[Internal link](https://app.asana.com/0/1201611182420182/1201909076676897/f)
=> feat: add pref to disable note status updates

packages/web/src/javascripts/Controllers/FilesController.ts, packages/web/src/javascripts/NativeMobileWeb/DownloadBlobOnAndroid.tsx, packages/web/src/javascripts/Utils/DownloadOrShareBasedOnPlatform.ts
[Internal link](https://app.asana.com/0/1201611182420182/1203064176254024/f)
=> fix: files download in mobile webview

packages/web/src/javascripts/Components/Preferences/Panes/General/Advanced/AdvancedSection.tsx, packages/web/src/javascripts/Components/Preferences/Panes/General/Advanced/Packages/PackageEntrySubInfo.tsx, packages/web/src/javascripts/Components/Preferences/PreferencesComponents/PreferencesGroup.tsx, packages/web/src/javascripts/Components/Preferences/PreferencesComponents/PreferencesPane.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203064176254036/f)
=> fix: preferences on mobile webview when zoomed in

packages/web/src/javascripts/App.tsx, packages/web/src/javascripts/Application/Device/WebOrDesktopDevice.ts
[Internal link](https://app.asana.com/0/1201611182420182/1203073480317673/f)
=> fix: android monospace font

packages/web/src/javascripts/Components/AttachedFilesPopover/PopoverFileItem.tsx, packages/web/src/javascripts/Components/AttachedFilesPopover/PopoverFileSubmenu.tsx, packages/web/src/javascripts/Components/FileContextMenu/FileMenuOptions.tsx, packages/web/src/javascripts/Components/Menu/MenuItem.tsx, packages/web/src/javascripts/Components/NoteTags/NoteTagsPanel.tsx, packages/web/src/javascripts/Components/NotesOptions/AddTagOption.tsx, packages/web/src/javascripts/Components/NotesOptions/ChangeEditorOption.tsx, packages/web/src/javascripts/Components/NotesOptions/ListedActionsOption.tsx, packages/web/src/javascripts/Components/NotesOptions/NotesOptions.tsx, packages/web/src/javascripts/Components/QuickSettingsMenu/QuickSettingsMenu.tsx, packages/web/src/javascripts/Components/QuickSettingsMenu/ThemesMenuButton.tsx, packages/web/tailwind.config.js
[Internal link](https://app.asana.com/0/1201611182420182/1203073480317671/f)
=> fix: increase context menu item font size on mobile

packages/models/src/Domain/Syncable/UserPrefs/PrefKey.ts, packages/styles/src/Styles/_colors.scss, packages/ui-services/src/Theme/ThemeManager.ts, packages/web/src/javascripts/Components/ApplicationView/ApplicationView.tsx, packages/web/src/javascripts/Components/DarkModeHandler/DarkModeHandler.tsx, packages/web/src/javascripts/Components/Preferences/Panes/Appearance.tsx, packages/web/src/javascripts/Components/QuickSettingsMenu/QuickSettingsMenu.tsx, packages/web/src/javascripts/Components/QuickSettingsMenu/ThemesMenuButton.tsx, packages/web/src/javascripts/Constants/PrefDefaults.ts, packages/web/src/stylesheets/_dark-mode.scss, packages/web/src/stylesheets/index.css.scss
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921931/f)
=> feat: add free dark mode

.github/workflows/mobile.release.test.yml
[Internal link](https://discord.com/channels/907326981744513044/907327873168326706/1026498247008714822)
=> chore: remove unused dev build gh release

packages/web/src/javascripts/Components/QuickSettingsMenu/FocusModeSwitch.tsx, packages/web/src/javascripts/Components/QuickSettingsMenu/PanelSettingsSection.tsx, packages/web/src/javascripts/Components/QuickSettingsMenu/QuickSettingsMenu.tsx, packages/web/src/javascripts/Components/QuickSettingsMenu/ThemesMenuButton.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203103528036261/f)
=> feat: change quick settings menu layout

packages/web/src/javascripts/Components/Footer/UpgradeNow.tsx, packages/web/src/javascripts/Components/PurchaseFlow/PurchaseFlowView.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203120505258666/f)
=> feat: open purchase flow when clicking upgrade cta with no account

packages/web/src/javascripts/App.tsx, packages/web/src/javascripts/Hooks/useMediaQuery.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203036051842541/f)
=> fix: potential fix for viewport height issue

packages/mobile/src/MobileWebAppContainer.tsx, packages/web/src/javascripts/Components/ChallengeModal/ChallengeModal.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921957/f)
=> feat: focus secure text entry after successful biometrics input

packages/web/src/javascripts/Components/Popover/PositionedPopoverContent.tsx, packages/web/src/stylesheets/_modals.scss
[Internal link](https://app.asana.com/0/1201611182420182/1203191622746759/f)
=> fix: "Forgot passcode" and "Switch workspace" lock screen options not working on mobile

packages/web/src/javascripts/Components/LinkedItems/ItemLinkAutocompleteInput.tsx, packages/web/src/javascripts/Hooks/useListKeyboardNavigation.ts
[Internal link](https://app.asana.com/0/1201611182420182/1203209000259718/f)
=> fix: link autocomplete input keyboard navigation

packages/mobile/src/Lib/Interface.ts, packages/services/src/Domain/Device/MobileDeviceInterface.ts, packages/web/src/javascripts/Application/Application.ts, packages/web/src/javascripts/Components/ChallengeModal/ChallengePrompt.tsx, packages/web/src/javascripts/NativeMobileWeb/MobileWebReceiver.ts
[Internal link](https://app.asana.com/0/1201611182420182/1203207764531840/f)
=> feat: auto-activate biometrics prompt when mobile regains focus

packages/mobile/src/Lib/Interface.ts, packages/web/src/javascripts/Application/Application.ts, packages/web/src/javascripts/Controllers/ViewControllerManager.ts, packages/web/src/javascripts/Event/ApplicationEventObserver.spec.ts, packages/web/src/javascripts/Event/ApplicationEventObserver.ts
[Internal link](https://app.asana.com/0/1201611182420182/1203251203595242/f)
=> fix: android screenshot privacy setting not working on app relaunch

packages/mobile/src/ColorSchemeObserverService.ts, packages/mobile/src/Lib/Interface.ts, packages/mobile/src/MobileWebAppContainer.tsx, packages/services/src/Domain/Application/WebApplicationInterface.ts, packages/services/src/Domain/Device/MobileDeviceInterface.ts, packages/snjs/lib/Client/ReactNativeToWebEvent.ts, packages/ui-services/src/Theme/ThemeManager.ts, packages/web/src/javascripts/Application/Application.ts, packages/web/src/javascripts/NativeMobileWeb/MobileWebReceiver.ts
[Internal link](https://app.asana.com/0/1201611182420182/1203251203595254/f)
=> fix: color scheme handling on mobile

packages/web/src/javascripts/Components/FilePreview/FilePreview.tsx, packages/web/src/javascripts/Components/FilePreview/FilePreviewError.tsx, packages/web/src/javascripts/Components/NoteView/NoteView.tsx, packages/web/src/javascripts/Components/NoteView/SuperEditor/Plugins/Commands.ts, packages/web/src/javascripts/Components/NoteView/SuperEditor/Plugins/EncryptedFilePlugin/Nodes/FileComponent.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203400971182195/f)
=> fix: lazy load embedded files in super editor

packages/blocks-editor/src/Lexical/Theme/editor.scss
[Internal link](https://app.asana.com/0/1201611182420182/1203421499232199/f)
=> feat: dim checked list items in super editor

packages/services/src/Domain/Event/WebAppEvent.ts, packages/ui-services/src/Keyboard/KeyboardCommandHandler.ts, packages/ui-services/src/Keyboard/KeyboardCommands.ts, packages/ui-services/src/Keyboard/KeyboardService.ts, packages/web/src/javascripts/Components/NoteView/SuperEditor/Plugins/ExportPlugin/ExportPlugin.ts, packages/web/src/javascripts/Components/NoteView/SuperEditor/SuperEditor.tsx, packages/web/src/javascripts/Components/NotesOptions/ClassNames.ts, packages/web/src/javascripts/Components/NotesOptions/NotesOptions.tsx, packages/web/src/javascripts/Components/NotesOptions/SpellcheckOptions.tsx, packages/web/src/javascripts/Components/NotesOptions/SuperNoteOptions.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203421499232215/f)
=> feat: export options for super notes

packages/blocks-editor/src/Lexical/Plugins/DraggableBlockPlugin/index.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203450165489235/f)
=> fix: Super note block drag-n-drop on mobile

packages/mobile/ios/Podfile.lock, packages/web/src/javascripts/Components/FilePreview/PreviewComponent.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203286512202003/f)
=> fix(mobile): PDF preview causing loop when biometrics are set to Immediate

packages/web/src/javascripts/Components/AttachedFilesPopover/PopoverFileItemAction.tsx, packages/web/src/javascripts/Controllers/FilePreviewModalController.ts, packages/web/src/javascripts/Controllers/FilesController.ts
[Internal link](https://app.asana.com/0/1201611182420182/1203512917756998/f)
=> feat: Added "Open" button to file upload success notification

packages/ui-services/src/Changelog/ChangelogService.ts, packages/ui-services/src/Changelog/ChangelogServiceInterface.ts, packages/web/src/javascripts/Components/Footer/Footer.tsx, packages/web/src/javascripts/Components/Footer/PreferencesButton.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203523747932045/f)
=> feat: Added "Whats New" indicator to Preferences button

packages/docs/docusaurus.config.js
The "Edit this page" link at the bottom of the pages updated to the new Github repo.
=> updated edit link

packages/blocks-editor/src/Lexical/Plugins/CollapsiblePlugin/CollapsibleContainerNode.ts, packages/blocks-editor/src/Lexical/Plugins/CollapsiblePlugin/CollapsibleContentNode.ts, packages/blocks-editor/src/Lexical/Plugins/CollapsiblePlugin/CollapsibleTitleNode.ts, packages/blocks-editor/src/Lexical/Plugins/CollapsiblePlugin/index.ts
[Internal link](https://app.asana.com/0/1201611182420182/1203573346335411/f)
=> feat: Persist collapsible block state in Super notes

packages/ui-services/src/Keyboard/KeyboardKey.ts, packages/web/src/javascripts/Components/FilesTableView/FilesTableView.tsx, packages/web/src/javascripts/Components/Table/CommonTypes.ts, packages/web/src/javascripts/Components/Table/Table.tsx, packages/web/src/javascripts/Components/Table/useTable.tsx
[Internal link](https://app.asana.com/0/0/1203615573305903/f)
=> feat: Added keyboard navigation to Files table view

packages/web/src/javascripts/Components/ContentListView/Daily/DailyContentList.tsx
[Internal link](https://app.asana.com/0/1203630241623298/1203722246414458/f)
=> fix: fixed issue where clicking on calendar cell in daily mode would not open correct note

packages/blocks-editor/src/Lexical/Plugins/FloatingTextFormatToolbarPlugin/index.css, packages/blocks-editor/src/Lexical/Plugins/FloatingTextFormatToolbarPlugin/index.tsx, packages/blocks-editor/src/Lexical/Utils/setFloatingElemPosition.ts
[Internal link](https://app.asana.com/0/1203630241623298/1203705853710619/f)
=> feat: Changed floating toolbar in Super to be always visible above keyboard on mobile

README.md
Fix the iOS link at the App Store.
=> Fix the iOS link at the App Store.

packages/ui-services/src/Import/SimplenoteConverter/SimplenoteConverter.ts
The converter was not transforming the contents of the notes into the format required for the Super editor, when Super was available.
=> fix: fix simplenote converter
