standardnotes/app

- app/assets/javascripts/app/frontend/controllers/editor.js
This refactors the controller a bit to insert 4 spaces when
a tab key is inserted inside of an editor, but in all other parts
of the app allow the user to use the tab key normally.
fix
https://github.com/standardnotes/desktop/issues/23
> Only handle tab key inside of editor

- app/assets/javascripts/app/frontend/controllers/editor.js
Once tab key is pressed, place the cursor 4 spaces away from
the location where the tab key was pressed.
This handles the case of when a tab key is pressed in the middle of
an existing note and the cursor was placed at the end of the document.
fix https://github.com/standardnotes/web/issues/50
> Reset the cursor

- app/assets/javascripts/app/services/directives/views/globalExtensionsMenu.js
This commit clears the "New Theme URL" after submitting the form in the same way that it is done for adding a new editor via URL.
> Clear New Theme URL after submit

- LICENSE
- package.json
Adds the LICENSE file which adds a couple of nice features in GitHub.
This commit also fixes the following warnings that appear when running `npm install`.
```
npm WARN neeto@1.0.0 No repository field.
npm WARN neeto@1.0.0 No license field.
```
> Add LICENSE file and fix npm warnings

- Dockerfile
The "run" instructions had a different image name from the "build" instructions.  This update just makes them work correctly together.
> Update Dockerfile Comments

- Dockerfile
- package-lock.json
- package.json
**Before updating the karma version in package.json:**
npm WARN notice [SECURITY] ws has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=ws&version=1.1.2 - Run npm i npm@latest -g to upgrade your npm version, and then npm audit to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run npm i npm@latest -g to upgrade your npm version, and then npm audit to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.2.0 - Run npm i npm@latest -g to upgrade your npm version, and then npm audit to get …
> Security fix/karma version

- Dockerfile
Added commented-out portions of Dockerfile that can be uncommented for use in production. Additional instruction was supplied in Dockerfile comments to change parameter in config/environments/production.rb for standard Docker best practices production configuration.
> Update Dockerfile for optional production use

- app/assets/javascripts/app/services/componentManager.js
- app/assets/javascripts/app/services/desktopManager.js
This allows the Desktop app to be notified when a component is registered and the iframe is ready.
Example usage: Observe a new component is registered to bind an eventListener on all new components.
> Added component activation/register observers

- app/assets/javascripts/app/controllers/notes.js
Referencing issue standardnotes/bounties#20
Just triggering it on pagination caused some issues because typing in the search box can trigger it as well so I added a flag to prevent that.
> fix(desktop): search highlight on pagination

- package.json
In commit https://github.com/standardnotes/web/commit/4f423301674cdae960d7e93de9d75728d6e35b07 it was removed only partialy making it fail on execution.
> Cleanup after bower removing

- app/assets/stylesheets/app/_notes.scss
Before/After:
Fixes: https://github.com/sn-extensions/simple-task-editor/issues/22
> Added support for theme color on Firefox progress bar

- app/assets/javascripts/app/controllers/footer.js
- app/assets/templates/footer.html.haml
Adds a title attribute to the dock icons in the footer to make it easier to identify which icon is for which theme. Requested: https://github.com/standardnotes/forum/issues/687
Excuse the added in mouse cursor ( print screen doesn't capture mouse D: )
> Dock Icon Titles/Names

- app/assets/javascripts/controllers/notes/notes.js
Wait for the note filter text to be cleared before reloading notes after a tag change.
(Fixes #363)
> Wait for the note filter text to be cleared before reloading notes after a tag change

- public/manifest.json
Currently, there's no `manifest.json` file that includes metadata like `name`, `description`, `icons`, etc.
> A user mentioned that the app icon on Chrome OS doesn't seem to be displaying properly, instead it just shows a black box with the letter S on it.
Here's the Standard Notes app without the `manifest.json` file:
---
And here's the App with said file:
> Web App Manifest

- app/assets/javascripts/directives/views/componentView.js
Fixes [desktop#498](https://github.com/standardnotes/desktop/issues/498)
Basically, `reloadComponent()` being async, it can sometime still be running after `componentView` has been destroyed which can cause some weird (and hard to trace down) problems, our app freeze on desktop being one of them.
I chose to fix this by adding and checking against a boolean which is bad for maintenance but is the least disruptive thing to do code-wise. @mobitar you have a better visibility on how `snjs`'s refactor would/will impact this file than me so if you think we can go further with some kind of cancelation mechanism (which standard JS promises don't have) let me know 👍
> Fix component actions still running after destruction

- app/assets/javascripts/services/preferencesManager.ts
Newly created accounts do not have a `UserPrefs` item:
The present PR aims to fix this issue by calling `this.loadSingleton();` if User preferences are `undefined`.
> fix: initialize userPreferences in preferencesManager

- app/assets/templates/directives/component-view.pug
- config/application.rb
This is regarding an issue pointed out by @not-a-robot-yet and fixes standardnotes/action-bar#8.
Since the Action Bar extension works in the desktop app, I decided to look at what was different in the web app. This was the error I got when using the Action Bar:
```
Content Security Policy: The page’s settings blocked the loading of a resource at data:text/plain;charset=utf-8,%3Cp%20dir… (“frame-src”).
```
I think it can be fixed by allowing `'data:'` in the `frame-src` CSP because this is how the Action Bar saves the note: 
```javascript
pom.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
``` 
I'm not too familiar with the web app, but perhaps you guys could weigh in on the security implications.
> fix: update CSP to allow action bar to download notes

- app/assets/javascripts/views/editor/editor-view.pug
- app/assets/javascripts/views/editor/editor_view.ts
This PR fixes the following bugs:
> fix: editor-view global display options

- app/assets/javascripts/directives/views/actionsMenu.ts
- app/assets/templates/directives/actions-menu.pug
The following PR refactors the legacy behavior for pre-immutability and adds the possibility to update properties for `actions` and `extensions`.
Required: https://github.com/standardnotes/snjs/pull/18
> refactor: actions menu

- app/assets/javascripts/views/editor/editor_view.ts
Currently the tags component doesn't get loaded or unloaded when we active/deactivate it from the extensions manager. This PR addresses that (though I would appreciate a review given my currently incomplete understanding of the editor view)
> fix: load/unload tags component on change

- app/assets/javascripts/views/abstract/pure_view_ctrl.ts
- app/assets/javascripts/views/editor/editor-view.pug
- app/assets/javascripts/views/editor/editor_view.ts
The editor stack should now work as expected: each note has its own state (with components being open/closed), and that state is synced between clients/restored on note change.
One of the things I did to help me fix this is I stopped relying on ComponentGroup to reduce the number of directions the data was moving in the editor view: it used to be from and to the component manager, as well as from and to the ComponentGroup. Now it's component manager -> editor view -> component manager. I'll look into using the ComponentGroup as a way to abstract the plumbing and interacting with the component manager so the editor view only has to talk to the ComponentGroup, but only after I'm done with making sure the editors and tags work well. I'll share my findings with @radko93 as well.
> Fix editor stack

- package.json
- webpack.config.js
> fix: ionicons not found on webpack dev server

- app/assets/javascripts/directives/views/actionsMenu.ts
- app/assets/templates/directives/actions-menu.pug
- package.json
> fix: incremental loading for actions

- .env.sample
- .gitignore
- README.md
- app/assets/javascripts/app.ts
- app/assets/javascripts/ui_models/application.ts
- app/assets/javascripts/ui_models/application_group.ts
- index.html
- package-lock.json
- package.json
- webpack.config.js
- webpack.dev.js
Using a combination of .env files and a webpack html template with sensible defaults makes for the most straightforward development quick-start experience possible
> feat: reduce number of steps needed to get going for local development

- app/assets/javascripts/directives/views/accountMenu.js
- app/assets/javascripts/strings.js
- package.json
This code is not future-proof but because `master` is so different from `develop` I'll have to develop the same thing again on `develop` anyway, where I'll actually check the account version (or do something else that doesn't have hardcoded version numbers)
> fix: prevent importing backup files with version > 003 

- app/assets/javascripts/directives/views/actionsMenu.ts
- app/assets/templates/directives/actions-menu.pug
> fix: upon extension error, loading spinner should be removed

- app/assets/javascripts/views/application/application_view.ts
the signin params should not be used outside of the demo app (would be insecure), so handle that case explicitly.
> fix: handle demo signin less generically

- Dockerfile
This fixes the same problem as https://github.com/standardnotes/syncing-server/pull/180.
> fix: run docker with root to fix crashing on Linux (undoes 62da387d3a)

- app/assets/javascripts/services/archiveManager.ts
- package.json
- yarn.lock
When downloading backups on web, send authorizedEncrypted as true so that encrypted backups are protected actions.
> feat: make encrypted backups protected

- package.json
- yarn.lock
* fix: remove `border-left` in `::webkit-scrollbar`
* fix: add web-components.js in index.html @johnny243 
* feat: component library for stylekit @johnny243 
* fix: change submodule urls from git@ to https://
Full changelog: https://github.com/standardnotes/StyleKit/compare/v2.2.0...v2.2.1
> chore(deps): bump sn-stylekit to 2.2.1

- app/assets/templates/directives/permissions-modal.pug
Before (note the missing space after "Learn more at":
After:
Adding an extra piped line is the recommended solution to this according to https://pugjs.org/language/plain-text.html#recommended-solutions (vs adding a leading or trailing space).
> fix missing whitespace in permissions-modal

- app/assets/javascripts/services/autolock_service.ts
- app/assets/javascripts/ui_models/app_state/app_state.ts
- app/assets/javascripts/views/abstract/pure_view_ctrl.ts
- Poll every 10ms (does this sound like a reasonable interval?) to check if the current date is larger than the lock app date, and thus we need to lock the app. Before we used to poll every second, and if the app was visible we'd lock it. By reducing the polling interval we can avoid the app flashing before locking itself, and by checking if we need to lock even if the app isn't visible we're allowing the app to lock itself even when it is on the background
- Remove listeners for window blur and window focus and remove setTimer for locking app, since by reducing the polling interval I think we could rely on polling only
Not sure if this approach makes sense so as usual feedback is very welcome 🙂
> fix: don't wait until regaining focus to lock app

- app/assets/javascripts/components/AccountMenu/Authentication.tsx
- app/assets/javascripts/components/AccountMenu/ErrorReporting.tsx
- app/assets/javascripts/components/AccountMenu/index.tsx
- show cursor as pointer when hovering "Advanced Options"
- show error reporting identifier as bold text
- when closing account menu with opened "Sign in" form and then reopening account menu, don't show "Sign in" form
> fix: the following is done:

- package.json
- yarn.lock
- Fixed a bug causing the Preferences menu to block when opening Preferences multiple times. 
- Related issues were opening the Security tab for the second time blocks the enable 2FA button, and similar...
- Cause was mobx store behaving inappropriately
> fix: preferences can be open multiple times

- app/assets/javascripts/preferences/panes/Extensions.tsx
Before:
After:
(Asana task: https://app.asana.com/0/1160981203938995/1201287063111826)
> fix: empty panel above 'Install Custom Extension' panel

- app/assets/javascripts/preferences/panes/extensions-segments/ConfirmCustomExtension.tsx
Internal link - https://app.asana.com/0/1200588672119490/1201366375943304
> fix: break long extension url text when it exceeds container width

- app/assets/javascripts/components/QuickSettingsMenu/QuickSettingsMenu.tsx
- app/assets/stylesheets/_focused.scss
Transition should only happen when toggling Focus Mode, not when manually resizing sections.
> fix: Width transition on manually resizing sections

- app/assets/javascripts/app.ts
- app/assets/javascripts/components/MultipleSelectedNotes.tsx
- app/assets/javascripts/components/PinNoteButton.tsx
- app/assets/javascripts/views/editor/editor-view.pug
- app/assets/stylesheets/_editor.scss
- app/assets/stylesheets/_sn.scss
- package.json
- yarn.lock
Asana task: https://app.asana.com/0/0/1201465631212053/f
> feat: Add "Pin selected notes" button to editor title bar

- app/assets/javascripts/components/AccountMenu/SignIn.tsx
Asana task: https://app.asana.com/0/1200980603427038/1201492678677936/f
> fix: Password toggle triggering on Enter when checkbox is focused

- app/assets/javascripts/components/TagsListItem.tsx
- app/assets/javascripts/ui_models/app_state/tags_state.ts
Up until now the tag views would use `application.referencesForItem` to count the number of notes references by a tag.
We moved the components to React recently and for simplicity we used SNJS: `tag.noteCounts` to count the notes referenced by a tag.
This exposed a bug where the editor might create a template note and create a reference to this note in a tag.
But if the editor discards the note it doesn't discard the reference.
Which creates orphan references that are counted by `tag.noteCounts` but not by `application.referencesForItem`
This patch reproduce the behavior of using `referencesForItem` until a better fix is implemented
(avoid orphan references and migrate users that have some).
Internal Issue:
https://app.asana.com/0/1201409453293587/1201550111577311
> hotfix/10.3.2: tags do not count orphan refs

- app/assets/javascripts/ui_models/panel_resizer.ts
https://app.asana.com/0/1201404190373500/1201560317881177/f
> fix: Panel resizing when using non-Plain editor

- app/assets/javascripts/components/NotesListItem.tsx
- app/assets/stylesheets/_notes.scss
[Internal link](https://app.asana.com/0/1201611182420182/1201738757752644/f)
> fix: note icons getting pushed by extra-long words

- app/assets/javascripts/components/NotesListOptionsMenu.tsx
- app/assets/javascripts/components/NotesView.tsx
- app/assets/javascripts/components/menu/MenuItem.tsx
- app/assets/javascripts/ui_models/app_state/notes_view_state.ts
- app/assets/stylesheets/_sn.scss
[Internal link](https://app.asana.com/0/1201653402817568/1201745533644578/f)
> fix: notes list options menu not toggling correctly

- app/assets/javascripts/components/NotesOptions/ListedActionsOption.tsx
[Internal link](https://app.asana.com/0/0/1201854567719015/1201870399995644/f)
> feat: add icon to listed group header

- app/assets/javascripts/components/ApplicationView.tsx
- app/assets/javascripts/components/Premium/usePremiumModal.tsx
- app/assets/javascripts/components/PremiumFeaturesModal.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1201843266656653/f)
> feat: redirect present subscribers to dashboard instead of plans page

- app/assets/javascripts/components/ChangeEditorButton.tsx
- app/assets/javascripts/components/NotesOptions/ChangeEditorOption.tsx
- app/assets/javascripts/components/NotesOptions/changeEditor/ChangeEditorMenu.tsx
[Internal link](https://app.asana.com/0/1201653402817568/1201919410778731/f)
> fix: toolbar change editor menu not updating

- app/assets/javascripts/components/AttachedFilesPopover/AttachedFilesButton.tsx
- app/assets/javascripts/components/AttachedFilesPopover/AttachedFilesPopover.tsx
- app/assets/javascripts/components/AttachedFilesPopover/PopoverFileItem.tsx
- app/assets/javascripts/components/Button.tsx
[Internal link](https://app.asana.com/0/1199942776723820/1201952151327819/f)
> fix: file popover not closing when click inside editor

- app/assets/javascripts/components/AttachedFilesPopover/AttachedFilesPopover.tsx
[Internal link](https://app.asana.com/0/1199942776723820/1201960955990992/f)
> fix: files popover illustration size

- app/assets/javascripts/components/Preferences/panes/backups-segments/EmailBackups.tsx
- app/assets/javascripts/components/Preferences/panes/backups-segments/cloud-backups/CloudBackupProvider.tsx
- app/assets/javascripts/components/Preferences/panes/backups-segments/cloud-backups/index.tsx
[Internal link](https://app.asana.com/0/1201653402817577/1202028817473232)
> fix: actually disable backup buttons if the user is not entitled

- app/assets/javascripts/components/Files/FilePreviewInfoPanel.tsx
- app/assets/javascripts/components/Files/FilePreviewModal.tsx
- app/assets/stylesheets/_sn.scss
[Internal link](https://app.asana.com/0/1199942776723820/1202031940659702/f)
> feat: add file information panel to file preview modal

- app/assets/javascripts/Services/ThemeManager.ts
- package.json
- yarn.lock
[Internal link](https://app.asana.com/0/0/1202049103273894/1202124334574789/f)
> fix: timed color scheme toast

- app/assets/javascripts/Components/ChallengeModal/ChallengeModal.tsx
- app/assets/javascripts/Components/ChallengeModal/ChallengePrompt.tsx
[Internal link](https://app.asana.com/0/1201404190373500/1202141587241290/f)
> fix: challenge modal styles

- app/assets/javascripts/Components/AttachedFilesPopover/AttachedFilesButton.tsx
- app/assets/javascripts/Components/AttachedFilesPopover/PopoverFileItem.tsx
- app/assets/javascripts/Components/AttachedFilesPopover/PopoverFileItemAction.tsx
- app/assets/javascripts/Components/AttachedFilesPopover/PopoverFileSubmenu.tsx
[Internal link](https://app.asana.com/0/1199942776723820/1202157106960505/f)
> feat: ask for password before previewing protected files

- app/assets/javascripts/Components/Preferences/Panes/Account/Files.tsx
- app/assets/javascripts/Components/Preferences/Panes/Account/index.tsx
- app/assets/javascripts/UIModels/AppState/AppState.ts
- app/assets/javascripts/UIModels/AppState/FilesState.ts
[Internal link](https://app.asana.com/0/1201653402817568/1202178087152257/f)
[Internal link 2](https://app.asana.com/0/1201653402817568/1202177959357567/f)
> feat: only fetch files quota when prefs are opened

- app/assets/javascripts/Components/AttachedFilesPopover/AttachedFilesButton.tsx
Prevents file drag-n-drop events from intercepting other drag-n-drop events.
> fix: early return file dnd if not dragging files

- app/assets/javascripts/Components/AttachedFilesPopover/AttachedFilesButton.tsx
- app/assets/javascripts/Components/AttachedFilesPopover/AttachedFilesPopover.tsx
- app/assets/javascripts/Components/AttachedFilesPopover/PopoverTabs.ts
[Internal link](https://app.asana.com/0/1201611182420182/1202224913318088/f)
> feat: drag file on tab button to switch to that tab

- app/assets/javascripts/Components/ContentListView/FileListItem.tsx
- app/assets/javascripts/Components/NoAccountWarning/NoAccountWarning.tsx
- app/assets/stylesheets/_sn.scss
- app/assets/stylesheets/_ui.scss
[Internal link](https://app.asana.com/0/0/1202315295894932/f)
> fix: file list item icon alignment

- packages/components/src/Packages/Editors/org.standardnotes.advanced-checklist/src/app/hooks.ts
- packages/components/src/Packages/Editors/org.standardnotes.advanced-checklist/src/features/tasks/CreateTask.tsx
- packages/components/src/Packages/Editors/org.standardnotes.advanced-checklist/src/features/tasks/TaskItem.tsx
[Internal link](https://app.asana.com/0/1202300765615141/1202464178850198/f)
> fix(advanced checklist): debounce saving task description/draft

- packages/web/src/javascripts/Components/FileView/FileView.tsx
- packages/web/src/javascripts/Controllers/FilesController.ts
Fixes an issue where once toggled, the protected overlay stay on even for files which were not protected.
> fix(web): file protected overlay not toggling off correctly

- packages/web/src/javascripts/Components/PasswordWizard/PasswordWizard.tsx
- packages/web/src/javascripts/Components/Preferences/Panes/Account/ChangeEmail/ChangeEmailForm.tsx
- packages/web/src/javascripts/Components/Preferences/Panes/Security/TwoFactorAuth/Bullet.tsx
- packages/web/src/javascripts/Components/Preferences/Panes/Security/TwoFactorAuth/ScanQRCode.tsx
- packages/web/src/javascripts/Components/SessionsModal/SessionsModal.tsx
- packages/web/src/javascripts/Components/Shared/ModalDialog.tsx
- packages/web/src/javascripts/Components/Shared/ModalDialogButtons.tsx
- packages/web/src/javascripts/Components/Shared/ModalDialogLabel.tsx
- packages/web/tailwind.config.js
[Internal link](https://app.asana.com/0/1201653402817568/1202562129044973/f)
> fix(web): update modal styles

- packages/web/src/javascripts/Application/Application.ts
- packages/web/src/javascripts/Components/ContentListView/FileListItem.tsx
- packages/web/src/javascripts/Components/ContentListView/NoteListItem.tsx
- packages/web/src/javascripts/Components/FileContextMenu/FileMenuOptions.tsx
- packages/web/src/javascripts/Components/FilePreview/ImagePreview.tsx
- packages/web/src/javascripts/Components/NotesContextMenu/NotesContextMenu.tsx
- packages/web/src/javascripts/Components/NotesOptions/NotesOptions.tsx
- packages/web/src/javascripts/Components/NotesOptions/NotesOptionsPanel.tsx
- packages/web/src/javascripts/Components/Preferences/Panes/General/Labs/Labs.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1202567797996911/f)
> feat: release Files view

- packages/components/src/Packages/Themes/org.standardnotes.theme-dynamic/src/main.scss
- packages/web/src/javascripts/Components/QuickSettingsMenu/FocusModeSwitch.tsx
- packages/web/src/stylesheets/_focused.scss
[Internal link](https://app.asana.com/0/1201611182420182/1202567330188851/f)
> fix: focus mode & dynamic panels on small screens

- packages/web/src/javascripts/Components/FilePreview/FilePreviewModal.tsx
https://github.com/standardnotes/forum/issues/1609#issue-1245512305
> fix: preview modal keyboard handling

- packages/desktop/app/javascripts/Renderer/Renderer.ts
Fixes the issue where on small window size, the popover header on the desktop app got hidden by the titlebar, which makes closing the popover not possible.
> fix: popover header getting hidden on desktop by titlebar

- packages/web/src/javascripts/App.tsx
- packages/web/src/stylesheets/_main.scss
On mobile, Chrome & Safari don't report the "correct" value for `vh` units, so `100vh` ends up being more than what it should be. This PR fixes it by adding an event listener for resize and orientationchange and sets the correct viewport height using CSS variables.
Discussed more here:
[Internal link](https://app.asana.com/0/1202707201988678/1202712080821937/f)
> fix: viewport height on mobile Chrome & Safari

- packages/web/src/javascripts/Components/TagAutocomplete/AutocompleteTagInput.tsx
fix: tag autocomplete list not visible on mobile
[Internal link](https://app.asana.com/0/1201611182420182/1202806979130588/f)
> fix: tag autocomplete result not clickable on iOS

- packages/web/src/javascripts/Components/ContentListView/ContentListView.tsx
- packages/web/tailwind.config.js
[Internal link](https://app.asana.com/0/1202205071929494/1202929351208011/f)
> fix: note panel resizing

- packages/mobile/src/App.tsx
- packages/mobile/src/AppStack.tsx
- packages/mobile/src/Screens/Settings/Sections/OptionsSection.tsx
- packages/web/src/javascripts/Components/ComponentView/ComponentView.tsx
- packages/web/src/javascripts/Components/Preferences/Panes/General/Defaults.tsx
- packages/web/src/javascripts/Components/Preferences/Panes/Security/Security.tsx
- Adds a setting in the native UI to fully switch to the webview
- Adds a setting in the webview to switch back to the native UI
> feat: add settings to fully switch between native/webview

- packages/web/src/javascripts/Components/NoteView/NoteView.tsx
[Internal app](https://app.asana.com/0/1201611182420182/1202997136490891/f)
> fix: move save status next to note actions on mobile

- packages/web/src/javascripts/Components/Tags/SmartViewsListItem.tsx
- packages/web/src/javascripts/Components/Tags/TagsListItem.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921883/f)
> fix: tag input auto-submitting when pressing space

- packages/web/src/javascripts/Components/Icon/PremiumFeatureIcon.ts
- packages/web/src/javascripts/Components/QuickSettingsMenu/FocusModeSwitch.tsx
- packages/web/src/javascripts/Components/QuickSettingsMenu/ThemesMenuButton.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921881/f)
> fix: hide focus mode and dynamic panel switches on mobile

- packages/web/src/javascripts/Components/ChangeEditor/ChangeEditorButton.tsx
- packages/web/src/javascripts/Components/ChangeEditor/ChangeEditorMenu.tsx
- packages/web/src/javascripts/Controllers/NotesController.ts
- packages/web/tailwind.config.js
[Internal link](https://app.asana.com/0/1201611182420182/1203014358109435/f)
> feat: show selected editor icon in change editor button

- packages/web/src/javascripts/Components/FileView/FileView.tsx
- packages/web/src/javascripts/Components/NoteView/NoteView.tsx
- packages/web/src/javascripts/Components/ProtectedItemOverlay/ProtectedItemOverlay.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921884/f)
> fix: protected overlay on mobile

- packages/web/src/javascripts/Components/Navigation/Navigation.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203022607956539/f)
> feat: add prefs button to navigation panel on mobile

- packages/web/src/javascripts/Components/NoteView/NoteView.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1198709526921878/f)
> feat: sticky header on mobile if plaintext note is scrolled

- packages/mobile/src/Lib/Interface.ts
- packages/services/src/Domain/Application/WebApplicationInterface.ts
- packages/services/src/Domain/Device/MobileDeviceInterface.ts
- packages/ui-services/src/Theme/ThemeManager.ts
- packages/web/src/javascripts/Application/Application.ts
- packages/web/src/javascripts/Components/ChallengeModal/BiometricsPrompt.tsx
- packages/web/src/javascripts/Components/FilePreview/FilePreview.tsx
- packages/web/src/javascripts/Components/FilePreview/PreviewComponent.tsx
- packages/web/src/javascripts/Components/FilePreview/isFilePreviewable.ts
- packages/web/src/javascripts/Components/Footer/UpgradeNow.tsx
- packages/web/src/javascripts/Components/Preferences/Panes/General/Defaults/CustomNoteTitleFormat.tsx
- packages/web/src/javascripts/Components/PurchaseFlow/PurchaseFlowFunctions.ts
- packages/web/src/javascripts/NativeMobileWeb/DownloadBlobOnAndroid.tsx
- packages/web/src/javascripts/NativeMobileWeb/ShareBlobOnMobile.ts
- packages/web/src/javascripts/NativeMobileWeb/useAndroidBackHandler.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203074136431479/f)
> feat: use native preview for pdf in mobile webview

- packages/docs/docs/self-hosting/docker.md
As it was before, the value "secret" in "secret_key" and "jegacy_jwt_secret" would be replaced by the key generated for "secret". This reduced the security of the keys as all three keys would be almost the same. By moving the command for secret to the bottom, this problem no longer occurs.
> fix(docs): Change order of sed commands

- packages/snjs/lib/Application/Application.ts
Can occur during webpack hot-reloading when changes made to ApplicationView, resulting in undefined state behavior.
> fix: prevent duplicate launch calls

- packages/blocks-editor/src/Editor/BlocksEditor.tsx
- packages/web/src/javascripts/Components/NoteView/SuperEditor/SuperEditor.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1203450165489237/f)
> fix: Make super note styling consistent with plaintext notes

- packages/mobile/html/Web.bundle/src/index.html
- packages/mobile/src/MobileWebAppContainer.tsx
[Internal link](https://app.asana.com/0/1203630241623298/1204478433429434/f)
> chore: show android system webview update prompt if app fails to load

- packages/web/src/javascripts/Components/ContentListView/FileListItem.tsx
- packages/web/src/javascripts/Components/ContentListView/NoteListItem.tsx
When attempting to access Standard Notes via a screen reader, the list of notes for a given tag are not detected as being clickable elements because they are defined as `div` elements instead of `input` or `button` elements:
This PR just adds `role="button"` to them so that they are properly detected by screen readers as clickable elements.
> ContentListItem accessibility bug

- packages/ui-services/src/Import/SimplenoteConverter/SimplenoteConverter.spec.ts
- packages/ui-services/src/Import/SimplenoteConverter/SimplenoteConverter.ts
- packages/ui-services/src/Import/SimplenoteConverter/testData.ts
SimplenoteConverter has a bug which causes it to only parse a title in notes which have *exactly* two lines. This is one of the issues addressed by [jamesgecko/simple-to-standard](https://github.com/jamesgecko/simple-to-standard).
Example data:
```json
{
"activeNotes": [
{
"id": "bb33231fc77e49e9b2f66b5d07b1159d",
"content": "Title One\r\nThis note has a title and one line of body!",
"..."
},
{
"id": "53c79c16-896f-43e5-80e5-a0f92c85330d",
"content": "Title Two\r\nThis note has a title and...\r\nmultiple lines...\r\nof body!",
"..."
},
{
"id": "1b105f4d24534d329ca8d99439219685",
"content": "\r\nThis note has only a body!",
"..."
},
],
"..."
}
```
Current behavior: the second note is given a title.
This PR fixes that issue by replacing an instance of String.prototype.split with a new …
> Bugfix: Fix Simplenote importer not titling multi-line documents

- packages/snjs/lib/Services/Settings/SettingsList.ts
- packages/snjs/mocha/settings.test.js
- packages/web/src/javascripts/Components/Preferences/Panes/Backups/EmailBackups.tsx
This setting is no longer interpreted on the server side thus it's not needed in the UI
> chore(web): remove unused setting for failed email backups - skip e2e

- README.md
The instructions to build the web app don't actually work.  You need to do `yarn install` in the root, and you also need to do the `yarn build:web` from the root or else dependency projects aren't correctly built.
To reproduce the problem, you can do this in docker and see it fail:
```Dockerfile
FROM node:20.11.1-alpine3.18
RUN apk add --no-cache git python3 make g++
RUN git clone https://github.com/standardnotes/app.git
WORKDIR /app/packages/web
RUN yarn build
```
Note that this will fail, but the following will not:
```Dockerfile
FROM node:20.11.1-alpine3.18
RUN apk add --no-cache git python3 make g++
RUN git clone https://github.com/standardnotes/app.git
WORKDIR /app
RUN yarn install
RUN yarn build:web
```
> Fixes web build instructions.

- packages/web/src/javascripts/Components/SuperEditor/Lexical/Theme/editor.scss
Before:
After:
This brings Standard Notes in line with the GitHub code block behavior when overflow occurs:
```
Here's usage information for git remote:
usage: git remote [-v | --verbose]
  or: git remote add [-t <branch>] [-m <master>] [-f] [--tags | --no-tags] [--mirror=<fetch|push>] <name> <url>
  or: git remote rename [--[no-]progress] <old> <new>
  or: git remote remove <name>
  or: git remote set-head <name> (-a | --auto | -d | --delete | <branch>)
  or: git remote [-v | --verbose] show [-n] <name>
  or: git remote prune [-n | --dry-run] <name>
  or: git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)...]
  or: git remote set-branches [--add] <name> <branch>...
  or: git remote get-url [--push] [--all] <name>
  or: git remote set-url [--push] <name> <newurl> …
```
> Update Super Notes to prevent code blocks from wrapping

- packages/services/src/Domain/User/UserService.ts
- packages/snjs/lib/Services/Session/SessionManager.ts
- packages/snjs/lib/Services/Session/cleanedEmailString.ts
- packages/snjs/mocha/keys.test.js
- packages/snjs/mocha/lib/factory.js
Prior to this fix, server would lowercase email on change automatically. However the client would generate the root key based on the raw user input. This means that changing email to "Foo@Bar.Com" would change your email to "foo@bar.com", but your password would only be correct on sign in if you entered "Foo@Bar.Com".
> fix: trim/lowercase email on email change

- packages/services/src/Domain/Preferences/LocalPrefKey.ts
- packages/web/src/javascripts/Controllers/PaneController/PaneController.ts
- packages/web/src/javascripts/Hooks/usePreference.tsx
This fixes the issue mentioned here: https://github.com/standardnotes/forum/issues/2423
I used `localStorage` to save the changes made by toggeling the panes.
Also I edited the initialization of the `panes` array, because otherwise all three panes would show up after reload for a short time and then dissapear again depending on your settings.
> fix: keep panes settings after reload

- packages/styles/src/Alert/Alert.ts
- packages/utils/src/Domain/Utils/Utils.ts
- packages/web/src/javascripts/Constants/Strings.ts
- packages/web/src/javascripts/Controllers/FilesController.ts
- packages/web/src/javascripts/Controllers/Navigation/NavigationController.ts
~~In the SKAlert component, both the title and the message of the dialog are being interpolated within the rest of the HTML, and then all of that HTML is set as `innerHTML` for the corresponding element. This means if the title or the message contain HTML themselves, it will be rendered within the dialog. This PR changes the implementation so that the initial template will include empty elements where the title and message will then be set using `textContent`, so that they're always displayed as strings.~~
Updated:
Because there are a few places where we intentionally use HTML within the strings for a dialog, I decided to go in a different direction and escape the HTML for notes/tags/files titles.
- Ultimately it could be better to move away from passing HTML to the alerts because there's …
> fix(SNOTES-480): display tag title as string in delete dialog

- packages/mobile/src/MobileWebAppContainer.tsx
- packages/snjs/lib/Client/ReactNativeToWebEvent.ts
- packages/ui-services/src/WebApplication/WebApplicationInterface.ts
- packages/web/src/javascripts/Application/WebApplication.ts
- packages/web/src/javascripts/NativeMobileWeb/MobileWebReceiver.ts
I've only been able to repro this on my production app by leaving the app open (minimized) overnight and then focusing on it again the next day. I'm not entirely sure what's going on, but I suspect that in those conditions either the effect that triggers the message to update the insets isn't fired, or the condition that checks for `didAppLaunch` before sending the message returns false.
This PR sets the CSS safe area inset vars using `injectJavascript` instead of `postMessage`. Injecting JS is actually the recommended way to pass information from RN to Web per the react-native-webview docs, and there's an example in the docs where this is used to update the background color of the webview https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#the-injectjava …
> fix(SNOTES-468): use injectJavascript to set safe area inset vars

- packages/models/src/Domain/Runtime/Display/Search/SearchUtilities.ts
- packages/models/src/Domain/Runtime/Display/Search/Types.ts
- packages/web/src/javascripts/Components/Tags/TagsList.tsx
- packages/web/src/javascripts/Components/Tags/TagsListItem.tsx
- packages/web/src/javascripts/Controllers/Navigation/NavigationController.ts
- Refactors tag search to only show the direct relevant tags and not any parent, siblings or children
- Double-clicking a tag when searching will clear search and scroll the tag into view.
https://github.com/user-attachments/assets/1ca68d95-141e-4815-9f8d-c26ab98a6f6b
> feat: Tag search will now only show the direct tag results instead of also showing the parent and siblings

- packages/models/src/Domain/Abstract/Payload/Implementations/PurePayload.spec.ts
- packages/models/src/Domain/Abstract/Payload/Implementations/PurePayload.ts
Although we have some logic preventing a payload from having a negative `created_at` or `updated_at` timestamp, when only the date fields are set and not the timestamp ones, the condition checking for a negative timestamp is not triggered. The timestamp is afterwards calculated from the date attributes, and if those correspond to a date before 1970-01-01, a negative timestamp is stored in the database.
This PR updates the logic so that it also checks for a `created_at` or `updated_at` field where the date is before 1970-01-01.
> fix: prevent setting negative item created at timestamps

- packages/web/src/javascripts/Components/SearchBar/SearchBar.tsx
Before:
On Firefox, pressing Tab when in the search bar "resets" the focus since we remove the option buttons from the DOM when the search input get unfocused. (On Chromium the body becomes the activeElement and when you press Tab again it intuitively starts from whatever is the next element after the search bar)
https://github.com/user-attachments/assets/4c89df51-1672-4f32-8120-812153e4d040
After:
We don't fully remove the options from the DOM and just use `display: none` to hide them and show them if focus is within the search bar container using `:focus-within`. This fixes the focus getting "reset" and also actually improves keyboard navigation since those options can now be selected using the keyboard instead of requiring mouse clicks. …
> chore: fix search bar focus handling

- packages/web/src/javascripts/Components/SuperEditor/Lexical/Theme/lists.scss
- packages/web/src/javascripts/Components/SuperEditor/Plugins/CheckListPlugin.tsx
- prevents on-screen keyboard from being shown (which causes a layout shift) when you just want to toggle a checklist item
- when page width is <450px, the size of the checkbox gets increased from `16px` to `20px` to make it slightly easier to touch
- makes checkmark size relative to the checkbox size using an svg, instead of using a border hack with hardcoded sizing
> chore(super notes): prevent keyboard from being shown when toggling checklist item and increase checkbox size on mobile
